_BASE_: Base-COCO-PanopticSegmentation.yaml
MODEL:
  BACKBONE:
    NAME: "build_stdc_backbone"
  YOSO:
    SIZE_DIVISIBILITY: 32
    # Structure
    NUM_CLASSES: 133
    NUM_STAGES: 2
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    #IN_FEATURES: ["x4", "x8", "x16", "x32"]
    #IN_FEATURES: ["STDC4", "STDC8", "STDC16", "STDC32"]
    HIDDEN_DIM: 64
    NUM_PROPOSALS: 100
    CONV_KERNEL_SIZE_2D: 1
    CONV_KERNEL_SIZE_1D: 3
    NUM_CLS_FCS: 1
    NUM_MASK_FCS: 1
    # Loss
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEMPERATIRE: 0.05
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: False
      PANOPTIC_ON: True
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.7 
OUTPUT_DIR: "output/yoso_resnet50_panoptic_seg_coco"